import React from 'react';
import "./globals.css";
import { Roboto_Mono } from "next/font/google";
import { Button } from "./ui/components/Button/Button";


import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body>
        <Button/>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
